# Generated by Django 5.1.1 on 2024-09-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
