# Generated by Django 5.1.1 on 2024-09-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_max', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
