# Generated by Django 5.1.1 on 2024-09-30 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('persona', '0002_alter_persona_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='curso',
            table='Curso',
        ),
    ]
