# Generated by Django 5.1.1 on 2024-10-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_profesor_id_alter_curso_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id_curso',
        ),
    ]
