# Generated by Django 5.1.1 on 2024-10-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_curso_estudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='capacidad_max',
            field=models.IntegerField(max_length=10),
        ),
    ]
