# Generated by Django 5.1.1 on 2024-10-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_alter_curso_capacidad_max'),
        ('persona', '0003_alter_persona_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='capacidad_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
